# ABBA BABA test
## Loading modules

In [15]:
import gcsfs #module for google cloud connection
import os
import allel
import zarr
import pandas as pd
import numpy

------

### Connect to google cloud ag1000g data 

In [16]:
gcs_orig = gcsfs.GCSFileSystem(project='malariagen-jupyterhub', token='cache')
gcs =  gcsfs.GCSFileSystem(project='malariagen-jupyterhub', token=gcs_orig.session.credentials)

In [17]:
phase2path = os.path.join("ag1000g-release", "phase2.AR1", "variation", "main", "zarr", "biallelic", "ag1000g.phase2.ar1.pass.biallelic")

In [18]:
gcsmap = gcsfs.mapping.GCSMap(phase2path, gcs=gcs)

----------------------------

Load Ag1000G data into python (metadata using pandas and genome using zarr and then scikit-allel)

In [19]:
metadata = pd.read_csv("samples.meta.txt", sep="\t")
metadata.describe()

ox_code         src_code population        country     location  \
0     AA0040-C  Twifo_Praso__E2      GHcol          Ghana  Twifo Praso   
1     AA0041-C  Twifo_Praso__H3      GHcol          Ghana  Twifo Praso   
2     AA0042-C      Takoradi_C7      GHcol          Ghana     Takoradi   
3     AA0043-C      Takoradi_H8      GHcol          Ghana     Takoradi   
4     AA0044-C     Takoradi_D10      GHcol          Ghana     Takoradi   
5     AA0048-C        Madina_A1      GHgam          Ghana       Madina   
6     AA0049-C        Madina_E3      GHcol          Ghana       Madina   
7     AA0050-C        Madina_E5      GHgam          Ghana       Madina   
8     AA0051-C  Twifo_Praso__C1      GHcol          Ghana  Twifo Praso   
9     AA0052-C  Twifo_Praso__F2      GHcol          Ghana  Twifo Praso   
10    AA0053-C  Twifo_Praso__A4      GHcol          Ghana  Twifo Praso   
11    AA0054-C      Takoradi_E7      GHcol          Ghana     Takoradi   
12    AA0055-C      Takoradi_B9      GHcol          Ghana     Takoradi   
13    AA0056-C     Takoradi_G10      GHcol          Ghana     Takoradi   
14    AA0060-C        Madina_C1      GHgam          Ghana       Madina   
15    AA0061-C        Madina_F3      GHgam          Ghana       Madina   
16    AA0063-C  Twifo_Praso__D1      GHcol          Ghana  Twifo Praso   
17    AA0064-C  Twifo_Praso__G2      GHcol          Ghana  Twifo Praso   
18    AA0066-C      Takoradi_G7      GHcol          Ghana     Takoradi   
19    AA0067-C      Takoradi_C9      GHcol          Ghana     Takoradi   
20    AA0068-C     Takoradi_H10      GHcol          Ghana     Takoradi   
21    AA0072-C        Madina_F1      GHgam          Ghana       Madina   
22    AA0073-C        Madina_H3      GHcol          Ghana       Madina   
23    AA0074-C        Madina_G5      GHcol          Ghana       Madina   
24    AA0075-C  Twifo_Praso__F1      GHcol          Ghana  Twifo Praso   
25    AA0076-C  Twifo_Praso__B3      GHcol          Ghana  Twifo Praso   
26    AA0077-C  Twifo_Praso__C4      GHcol          Ghana  Twifo Praso   
27    AA0080-C     Takoradi_A11      GHcol          Ghana     Takoradi   
28    AA0084-C        Madina_A2      GHgam          Ghana       Madina   
29    AA0085-C        Madina_A4      GHgam          Ghana       Madina   
...        ...              ...        ...            ...          ...   
1112  AY0056-C        Tia_aPM_8      CIcol  Cote d'Ivoire     Tiassale   
1113  AY0057-C       Tia_aPM_17      CIcol  Cote d'Ivoire     Tiassale   
1114  AY0058-C       Tia_aPM_25      CIcol  Cote d'Ivoire     Tiassale   
1115  AY0059-C       Tia_aPM_36      CIcol  Cote d'Ivoire     Tiassale   
1116  AY0060-C       Tia_aPM_30      CIcol  Cote d'Ivoire     Tiassale   
1117  AY0061-C        Tia_dPM_3      CIcol  Cote d'Ivoire     Tiassale   
1118  AY0062-C       Tia_dPM_10      CIcol  Cote d'Ivoire     Tiassale   
1119  AY0063-C       Tia_dPM_18      CIcol  Cote d'Ivoire     Tiassale   
1120  AY0064-C       Tia_dPM_25      CIcol  Cote d'Ivoire     Tiassale   
1121  AY0065-C       Tia_dPM_48      CIcol  Cote d'Ivoire     Tiassale   
1122  AY0066-C       Tia_dPM_54      CIcol  Cote d'Ivoire     Tiassale   
1123  AY0067-C        Tia_aPM_6      CIcol  Cote d'Ivoire     Tiassale   
1124  AY0068-C       Tia_aPM_15      CIcol  Cote d'Ivoire     Tiassale   
1125  AY0069-C       Tia_aPM_24      CIcol  Cote d'Ivoire     Tiassale   
1126  AY0070-C       Tia_aPM_35      CIcol  Cote d'Ivoire     Tiassale   
1127  AY0072-C        Tia_dPM_2      CIcol  Cote d'Ivoire     Tiassale   
1128  AY0074-C       Tia_dPM_17      CIcol  Cote d'Ivoire     Tiassale   
1129  AY0076-C       Tia_dPM_47      CIcol  Cote d'Ivoire     Tiassale   
1130  AY0077-C       Tia_dPM_53      CIcol  Cote d'Ivoire     Tiassale   
1131  AY0078-C        Tia_aPM_5      CIcol  Cote d'Ivoire     Tiassale   
1132  AY0079-C       Tia_aPM_14      CIcol  Cote d'Ivoire     Tiassale   
1133  AY0080-C       Tia_aPM_23      CIcol  Cote d'Ivoire     Tiassale   
1134  AY008

Taking 4 populations for the ABBA BABA test and subset

In [20]:
pop_select = metadata.population.isin({'BFcol', 'GHcol', 'BFgam', 'AOcol'}).values
pop_select

array([ True,  True,  True, ..., False, False, False])

In [21]:
pop_subset = metadata[pop_select]
pop_subset.head()

ox_code         src_code population country     location         site  \
0  AA0040-C  Twifo_Praso__E2      GHcol   Ghana  Twifo Praso  Twifo Praso   
1  AA0041-C  Twifo_Praso__H3      GHcol   Ghana  Twifo Praso  Twifo Praso   
2  AA0042-C      Takoradi_C7      GHcol   Ghana     Takoradi     Takoradi   
3  AA0043-C      Takoradi_H8      GHcol   Ghana     Takoradi     Takoradi   
4  AA0044-C     Takoradi_D10      GHcol   Ghana     Takoradi     Takoradi   

     contributor        contact  year m_s sex  n_sequences  mean_coverage  \
0  David Weetman  David Weetman  2012   M   F     95033368          30.99   
1  David Weetman  David Weetman  2012   M   F     95843804          31.70   
2  David Weetman  David Weetman  2012   M   F    107420666          35.65   
3  David Weetman  David Weetman  2012   M   F     95993752          29.46   
4  David Weetman  David Weetman  2012   M   F    103044262          33.67   

  ebi_sample_acc  latitude  longitude  
0      ERS311878   5.60858   -1.54926  
1      ERS311886   5.60858   -1.54926  
2      ERS311894   4.91217   -1.77397  
3      ERS311902   4.91217   -1.77397  
4      ERS311910   4.91217   -1.77397

In [22]:
calldata= zarr.Group(gcsmap, read_only=True)

In [23]:
g = calldata["3L"]["calldata/GT"]

In [24]:
geno = allel.GenotypeChunkedArray(g)
geno

<GenotypeChunkedArray shape=(7897666, 1142, 2) dtype=int8 chunks=(524288, 61, 2)
   nbytes=16.8G cbytes=-1 cratio=-18038269144.0
   compression=blosc compression_opts={'cname': 'zstd', 'clevel': 1, 'shuffle': -1, 'blocksize': 0}
   values=zarr.core.Array>

Subset genotype to my 4 populations

In [25]:
geno_subset = geno.subset(sel1=pop_select)
geno_subset

<GenotypeChunkedArray shape=(7897666, 300, 2) dtype=int8 chunks=(7713, 300, 2)
   nbytes=4.4G cbytes=189.0M cratio=23.9
   compression=blosc compression_opts={'cname': 'lz4', 'clevel': 5, 'shuffle': 1, 'blocksize': 0}
   values=zarr.core.Array>

In [26]:
grp = pop_subset.groupby("population")

In [27]:
grp_indices = grp.indices
grp_indices

{'AOcol': array([222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
        235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
        248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
        261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
        274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
        287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299]),
 'BFcol': array([ 56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
         72,  73,  74,  75,  76,  77,  78,  82,  83,  84,  94,  95,  96,
         97,  98, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 150, 155, 156, 158, 159, 160, 163, 164, 165, 166,
        167, 168, 169, 171, 175, 178, 181, 183, 184, 186, 187, 188, 189,
        190, 196, 197, 200, 201, 204, 205, 213, 216, 219]),
 'BFgam': array([ 55,  69,  70,  71,  79,  80,  81,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  99, 100, 10

In [28]:
ac_subpops = geno_subset.count_alleles_subpops(grp_indices)
ac_subpops

<AlleleCountsChunkedTable shape=(7897666,) dtype=[('AOcol', '<i4', (2,)), ('BFcol', '<i4', (2,)), ('BFgam', '<i4', (2,)), ('GHcol', '<i4', (2,))]
   nbytes=241.0M cbytes=24.3M cratio=9.9
   values=allel.chunked.storage_zarr.ZarrTable>

In [29]:
abba_3L = allel.patterson_d(ac_subpops['AOcol'], ac_subpops['BFcol'], ac_subpops['BFgam'], ac_subpops['GHcol'])
abba_3L

(array([ 0.,  0.,  0., ...,  0., -0.,  0.]),
 array([0., 0., 0., ..., 0., 0., 0.]))

In [34]:
len(abba_3L[0])

7897666

In [35]:
min(abba_3L[0])

-0.6061429512516469

In [36]:
max(abba_3L[0])

0.8047658862876255